### ISSUE TITLE
No longer compiling on Ubuntu 18.04

### ISSUE THREAD

**Issue by jasonheine** [trusch/libbcrypt#10]
I've installed several servers using your instruction, however it's no longer working. I've removed and re-tried several times. I even tried from the Aug 8 build. 

When I run the following command:
g++ --std=c++11 -lbcrypt main.cpp

I'm now getting the following error:
main.cpp:1:10: fatal error: bcrypt/BCrypt.hpp: No such file or directory
 #include "bcrypt/BCrypt.hpp"

Install Logs:

cmake ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Configuring done
-- Generating done
-- Build files have been written to: /var/dtBuild/libbcrypt/build

make && make install && ldconfig
Scanning dependencies of target bcrypt
[ 12%] Building C object CMakeFiles/bcrypt.dir/src/bcrypt.c.o
[ 25%] Building C object CMakeFiles/bcrypt.dir/src/crypt_blowfish.c.o
[ 37%] Building C object CMakeFiles/bcrypt.dir/src/crypt_gensalt.c.o
[ 50%] Building C object CMakeFiles/bcrypt.dir/src/wrapper.c.o
[ 62%] Building ASM object CMakeFiles/bcrypt.dir/src/x86.S.o
[ 75%] Linking C shared library libbcrypt.so
[ 75%] Built target bcrypt
Scanning dependencies of target bcrypt_test
[ 87%] Building CXX object CMakeFiles/bcrypt_test.dir/src/main.cpp.o
[100%] Linking CXX executable bcrypt_test
[100%] Built target bcrypt_test
[ 75%] Built target bcrypt
[100%] Built target bcrypt_test
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/libbcrypt.so.1.0.0
-- Up-to-date: /usr/local/lib/libbcrypt.so.1
-- Up-to-date: /usr/local/lib/libbcrypt.so
-- Installing: /usr/local/include/BCrypt.hpp
-- Up-to-date: /usr/local/include
-- Up-to-date: /usr/local/include/bcrypt
-- Installing: /usr/local/include/bcrypt/ow-crypt.h
-- Installing: /usr/local/include/bcrypt/bcrypt.h
-- Installing: /usr/local/include/bcrypt/crypt_blowfish.h
-- Installing: /usr/local/include/bcrypt/crypt.h
-- Installing: /usr/local/include/bcrypt/crypt_gensalt.h

**Comment by trusch** [comment]
Strange, looks like /usr/local/include is not included in your header search pathes. 

Please try to add `-I /usr/local/include` to your build command and look if this helps.

**Comment by jasonheine** [comment]
I ran the following command:
g++ -I /usr/local/include --std=c++11 -lbcrypt main.cpp

And still received the following error:
main.cpp:1:10: fatal error: bcrypt/BCrypt.hpp: No such file or directory
 #include "bcrypt/BCrypt.hpp"

Ran the following command to confirm:
ls -lh /usr/local/include/

total 8.0K
drwxr-xr-x 2 root root 4.0K Nov 14 13:31 bcrypt
-rw-r--r-- 1 root root  792 Nov 14 13:31 BCrypt.hpp

Shouldn't BCrypt.hpp be in the bcrypt folder?

I checked another Ubuntu 18.04 server and that file did indeed copy to the bcrypt folder.

I copied the libbcrypt folder from that server to this one, did all the commands to build and this time my project compiled. 

So, I'm not sure if the latest code in the repo has a flaw installing, but I'm looking at the folder from the other server and the date on the files is Oct 18 at 19:11

**Comment by tfleck** [comment]
I just ran into this issue trying to install and run this library on Cloud9 Ubuntu
It appears that BCrypt.hpp isn't going into the right include folder with the other header files. Adding PATTERN "*.hpp" to the install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/include/ DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
	FILES_MATCHING PATTERN "*.h" got it to compile properly for me

Also, cmake puts the library files in /usr/local/lib/x86_64-linux-gnu which wasn't included by default for me, I had to add it to x86_64-linux-gnu.conf and redo sudo ldconfig to get it to run. Maybe install to /usr/lib/x86_64-linux-gnu? That was included by default

I was able to get the demo to run after that
I hope this helps!

**Comment by trusch** [comment]
Could you open a PR for that @tfleck?

**Comment by kriive** [comment]
Whoops! I the last PR I forgot to move BCrypt.hpp to bcrypt/BCrypt.hpp.
Proposed fix in #11

**Comment by kriive** [comment]
> Also, cmake puts the library files in /usr/local/lib/x86_64-linux-gnu which wasn't included by default for me, I had to add it to x86_64-linux-gnu.conf and redo sudo ldconfig to get it to run. Maybe install to /usr/lib/x86_64-linux-gnu? That was included by default.

@tfleck CMake tells make to install the lib in a directory specified by CMAKE_INSTALL_LIBDIR macro, which is very platform dependent ([documentation here](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html))
I guess you can override it using `cmake -DCMAKE_INSTALL_LIBDIR=/somewhere/you/want ..` (untested, let me know if this addresses your issue)
