### ISSUE TITLE
Linker Problem?

### ISSUE THREAD

**Issue by EVO-B** [trusch/libbcrypt#16]
I am trying to test this lib on  and keep running into this problem on compilation:

/tmp/ccM0Lvac.o: In function `BCrypt::generateHash(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
main.cpp:(.text._ZN6BCrypt12generateHashERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi[_ZN6BCrypt12generateHashERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi]+0x44): undefined reference to `bcrypt_gensalt'
main.cpp:(.text._ZN6BCrypt12generateHashERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi[_ZN6BCrypt12generateHashERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi]+0xb0): undefined reference to `bcrypt_hashpw'
collect2: error: ld returned 1 exit status

any idea why?
On Ubuntu 18.04 and using gcc

**Comment by kriive** [comment]
I'm investigating this right now, can you confirm if the bug still persists on clang++?
`clang++ -std=c++11 -lbcrypt main.cpp`

**Comment by kriive** [comment]
[This](https://stackoverflow.com/a/12748882) solved the issue for me, can you confirm?

**Comment by EVO-B** [comment]
Thank you very much, this worked for me, this is one of my first independent projects so I apologize if I was vague.
