### ISSUE TITLE
Why does the example in the readme create an object when both the functions in the BCrypt class are static?

### ISSUE THREAD

**Issue by HemilTheRebel** [trusch/libbcrypt#19]
I recently observed that the code complete of my editor showed me the syntax of `validatePassword` and it contained the word static. I was shocked! I thought they were member functions. I opened BCrypt.hpp only to find both `validatePassword` and `generateHash` are static! 

After some thought it made sense to me that those functions are static but this makes me wonder by does the readme create BCrypt object when according to my knowledge, it should be a no-op. And if there is no good reason to create objects, does it make sense to use a namespace instead of a class?

**Comment by kriive** [comment]
It's probably a typo. Going to submit a pull request with a simple edit to README.md to reflect that.

Regarding namespaces vs classes, namespaces functions may actually be a better fit, feel free to submit a PR. We should check if it breaks existing code that depends on libbcrypt first.

**Comment by HemilTheRebel** [comment]
@kriive replacing namespace is bound to break code for people who used bcrypt wrongly creating objects.
