### ISSUE TITLE
Usage errors on Windows 10

### ISSUE THREAD

**Issue by gaberau** [trusch/libbcrypt#21]
Trying to utilize this on Windows 10 and I can't get my compiler to quantify the include statement. Everytime it throws a `fatal error: bcrypt/BCrypt.hpp: No such file or directory`. However, I have `-lbcrypt` included in my compiler. Has anyone encountered this error before?

**Comment by trusch** [comment]
You need to add the include directory to your commandline (e.g. g++ -I
path/to/header)

gabe rau <notifications@github.com> schrieb am So., 13. Okt. 2019, 03:10:

**Comment by gaberau** [comment]
Alright, I tried doing as you reccommended, here is the command that I gave to the terminal: `g++ -o example.exe -l"C:\Users\Person with a name\Desktop\libbcrypt\include\bcrypt" bcrypt_example.cpp`. However, this has not resolved the error and the compiler keeps throwing `bcrypt_example.cpp:2:10: fatal error: BCrypt.hpp: No such file or directory
 #include "BCrypt.hpp"
          ^~~~~~~~~~~~
compilation terminated.`

**Comment by trusch** [comment]
The command line flag to specify the directories for header files is `-I`, in words `dash-capital-i`. @thunderbuns

**Comment by HemilTheRebel** [comment]
Shouldn't this be closed?
