### ISSUE TITLE
Problem using [SOLVED]

### ISSUE THREAD

**Issue by kleberholtz** [trusch/libbcrypt#31]
I'm having problems using the library, here are some information below:

`#include "bcrypt/BCrypt.hpp" ` Is included on file.

### Function:
```
std::string transformToBCRYPT(std::string plainText, bool upperCase)
{
  std::string hash = BCrypt::generateHash(plainText.c_str());

	if(upperCase)
		return std::string(hash);

	return asLowerCaseString(std::string(hash));
}
```

### Error:
```
/usr/bin/ld: objects/tools.o: in function `transformToBCRYPT(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, int)':
tools.cpp:(.text+0x14b4): undefined reference to `bcrypt_gensalt'
/usr/bin/ld: tools.cpp:(.text+0x14d4): undefined reference to `bcrypt_hashpw'
collect2: error: ld returned 1 exit status
```

### How to solve:
My problem has been solved to adding flag `-lbcrypt`  in Makefile project.

**Comment by FlavaSava** [comment]
Did you compile the library and add it as input to the linker?

See [README](https://github.com/trusch/libbcrypt/blob/master/README.md) for instructions

**Comment by kleberholtz** [comment]
Yes, I compiled the repository, installed it with `sudo make install` as per the instructions in the [README](https://github.com/trusch/libbcrypt/blob/master/README.md),
and pointed in my project's Makefile to see the libraries in the `/usr/local/include` directory
