### ISSUE TITLE
How to build for ARM architecture?

### ISSUE THREAD

**Issue by PonasKovas** [trusch/libbcrypt#7]
Just how can I make it work on ARM instead of AMD64?

**Comment by shivamdev-lgtm** [comment]
If it's for android, there's already an implementation of it in Java..
Or u can use NDK

**Comment by PonasKovas** [comment]
No I want to use this library on a raspberry pi.

**Comment by kriive** [comment]
@PonasKovas I'll look into this in the next few days, when I revive my Raspberry Pi from dead.
Why can't you build libbcrypt on ARM? Did CMake complain about something?

**Comment by kriive** [comment]
ARM assembler didn't understand a stack-executable protection left out of the i386 include guard in x86.S (and thus not needed by ARM compilation).

In #8 I have covered the error and corrected some other CMake stuff.
