### ISSUE TITLE
Build successful but failed test on windows 7

### ISSUE THREAD

**Issue by xdien** [trusch/libbcrypt#9]
I tried to build on windows 7, mingw 5.3.0, qt 5.7, with the command:

> mkdir build
> cd build
> cmake -G"MinGW Makefiles" ../
> mingw32-make

I disabled -fPIC flags and build successful.
> D:\libbcrypt\build>bcrypt_test.exe
`generate hash... terminate called after throwing an instance of 'std::runtime_error'
  what():  bcrypt: can not generate salt
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.`

But running the bcrypt_test fail.
I tried to find out a lot of information on stackoverflow but all the same things a bug like!

**Comment by trusch** [comment]
I'm really sorry for this, but I can't maintain that for windows. If you find the root cause please share and I'll be happy accepting your PR

**Comment by kriive** [comment]
I have no Windows box to test this atm. I should be able to have a look at the issue on monday

**Comment by xdien** [comment]
I think the problem in the function
```
int bcrypt_gensalt(int factor, char salt[BCRYPT_HASHSIZE]){
    ...
    fd = open("/dev/urandom", O_RDONLY);
    ...
}
```

windows does not have "/dev/urandom"
I found another post on stackoverflow to replace /dev/urandom on windows https://stackoverflow.com/questions/51748439/how-to-use-bcrypt-on-windows . But I do not know how to make it work.

**Comment by kriive** [comment]
On Windows we could use [this](https://docs.microsoft.com/en-us/windows/desktop/api/bcrypt/)

**Comment by xdien** [comment]
I also read some bcrypt documentation on windows. I'm trying it but hopefully this library can run on multiple platforms. Now this problem can be closed.

**Comment by kriive** [comment]
I will try to add support to Windows extending this library and wrapping when necessary the appropriate calls to Windows' native API. But no promises on ETA haha

**Comment by xdien** [comment]
Oh nice ;)

**Comment by LiamKarlMitchell** [comment]
Reading here it seems that bcrypt in windows sdk is not actually for bcrypt but for Microsoft's "BestCrypt".

https://stackoverflow.com/questions/9711568/does-winapis-bcrypt-h-actually-support-bcrypt-hashing
```Short version
No, bcrypt is short for bestcrypt. And, no, it doesn't support bcrypt (blowfish crypt) password hashing.```
